version: "3"

services:
  mysql-cluster-mgm:
    build: images/mysql-cluster
    container_name: "mysql-cluster-mgm"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      NODE_TYPE: "management"
    volumes:
      - ./confs/cluster_my.cnf:/etc/my.cnf
      - ./confs/cluster.cnf:/etc/mysql-cluster.cnf
      - ./data/cluster_mgm:/var/lib/mysql
  mysql-cluster-dn1:
    build: images/mysql-cluster
    container_name: "mysql-cluster-dn1"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      NODE_TYPE: "data"
    volumes:
      - ./data/cluster_dn1:/var/lib/mysql
    depends_on:
      - mysql-cluster-mgm
  mysql-cluster-dn2:
    build: images/mysql-cluster
    container_name: "mysql-cluster-dn2"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      NODE_TYPE: "data"
    volumes:
      - ./data/cluster_dn2:/var/lib/mysql
    depends_on:
      - mysql-cluster-mgm
  mysql-cluster-sv1:
    build: images/mysql-cluster
    container_name: "mysql-cluster-sv1"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      NODE_TYPE: "sql"
    depends_on:
      - mysql-cluster-dn1
      - mysql-cluster-dn2
