version: "3"

services:
  mysql-master:
    build: images/mysql
    container_name: "mysql-master"
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
      - ${DEFAULT_CNF}
      - ./confs/replica_master.cnf:/etc/mysql/conf.d/replica_master.cnf
      - ./scripts/replica/init_master.sql:/docker-entrypoint-initdb.d/init_master.sql
      - ./data/replica_mysql_master:/var/lib/mysql
  mysql-slave:
    build: images/mysql
    container_name: "mysql-slave"
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
      - ${DEFAULT_CNF}
      - ./confs/replica_slave.cnf:/etc/mysql/conf.d/replica_slave.cnf
      - ./scripts/replica/init_slave.sql:/docker-entrypoint-initdb.d/init_slave.sql
      - ./data/replica_mysql_slave:/var/lib/mysql
    depends_on:
      - mysql-master