apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-cluster-sv1
  name: mysql-cluster-sv1
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: bench
    image: ambiente_mysql_cluster
    imagePullPolicy: IfNotPresent
    name: mysql-cluster-sv1
    command: ["/entrypoint.sh"]
    args: ["mysqld"]
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /etc/my.cnf
      subPath: my.cnf
      name: mysql-cluster-sv1-my-confs
  volumes:
    - name: mysql-cluster-sv1-my-confs
      configMap:
        name: mysql
        items:
        - key: cluster_my.cnf
          path: my.cnf