apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-cluster-dn1
  name: mysql-cluster-dn1
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: bench
    image: ambiente_mysql_cluster
    imagePullPolicy: IfNotPresent
    name: mysql-cluster-dn1
    command: ["/entrypoint.sh"]
    args: ["ndbd"]
    ports:
    - containerPort: 2202
    volumeMounts:
    - mountPath: /etc/my.cnf
      subPath: my.cnf
      name: mysql-cluster-dn1-my-confs
  volumes:
    - name: mysql-cluster-dn1-my-confs
      configMap:
        name: mysql
        items:
        - key: cluster_my.cnf
          path: my.cnf
  nodeSelector:
    clst: dn1