apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-sv1
spec:
  selector:
    app: mysql-cluster-sv1
  type: NodePort
  ports:
  - name: "mysqld"
    port: 3306
    targetPort: 3306
    nodePort: 30036